### BDM 3014 - Introduction to Artificial Intelligence -Project work

### Project- Movie Recommendation System

#### importing packages

In [1]:
import numpy as np
import pandas as pd
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject

In [2]:

import re

# import movies data
file_movie = './tmdb_5000_movies.csv'
movies = pd.read_csv(file_movie)

In [3]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [4]:

# import credits data
file_credit = "./tmdb_5000_credits.csv"
credits = pd.read_csv(file_credit)
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [5]:

# merging the two different datasets of movies and credits, and making the resultant "movies"
movies = movies.merge(credits, on='title')

In [6]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [7]:

print(movies.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB
None

In [8]:

# Out of the various different fields, we are considering to take following crucial fields for data analysis
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [9]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [10]:
# Finding out the Null values in particular fields
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
# Dropping the  rows where overview is NULL
movies.dropna(inplace=True)

C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\15401317.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [12]:
movies.duplicated().sum()

0

In [13]:
import ast

In [14]:

# Function to get the values of the key "name"
def convert(input):
    list = []
    for i in ast.literal_eval(input):
        list.append(i['name'])
    return list

In [15]:
movies['genres'] = movies['genres'].apply(convert)

C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\1189516248.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(convert)

In [16]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [17]:
movies.head()['genres']

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [18]:
movies['keywords'] = movies['keywords'].apply(convert)

C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\3328512696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(convert)

In [19]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united statesâ€“mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [20]:
movies.head()['keywords']

0    [culture clash, future, space war, space colon...
1    [ocean, drug abuse, exotic island, east india ...
2    [spy, based on novel, secret agent, sequel, mi...
3    [dc comics, crime fighter, terrorist, secret i...
4    [based on novel, mars, medallion, space travel...
Name: keywords, dtype: object

In [21]:
movies.head()['cast']

0    [{"cast_id": 242, "character": "Jake Sully", "...
1    [{"cast_id": 4, "character": "Captain Jack Spa...
2    [{"cast_id": 1, "character": "James Bond", "cr...
3    [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4    [{"cast_id": 5, "character": "John Carter", "c...
Name: cast, dtype: object

In [22]:
# The Field 'cast' has different dictionary within it , which has information regarding the castField
# Converting string of list into list using literal_eval() function
def convertDict(castField):
    list = []
    counter = 0
    for i in ast.literal_eval(castField):
        while (counter) < 3:
            list.append(i['name'])
            counter += 1
        else:
            break
    return list

In [23]:
movies['cast'] = movies['cast'].apply(convert)

C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\2217188125.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(convert)

In [24]:
movies['cast']

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805    [Edward Burns, Kerry BishÃ©, Marsha Dietlein, C...
4806    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4806, dtype: object

In [25]:
# From crew we will filter out name of the director of the movie
def get_director(crewDict):
    list = []
    for i in ast.literal_eval(crewDict):
        if i['job'] == 'Director':
            list.append(i['name'])
    return list

In [26]:
movies['crew'] = movies['crew'].apply(get_director)

C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\338316728.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(get_director)

In [27]:
movies['crew']

0                                [James Cameron]
1                               [Gore Verbinski]
2                                   [Sam Mendes]
3                            [Christopher Nolan]
4                               [Andrew Stanton]
                          ...
4804                          [Robert Rodriguez]
4805                              [Edward Burns]
4806                               [Scott Smith]
4807                               [Daniel Hsia]
4808    [Brian Herzlinger, Jon Gunn, Brett Winn]
Name: crew, Length: 4806, dtype: object

In [28]:
# spliting the data and made a list of them i.e. space replaced by commas
movies['overview'] = movies['overview'].apply(lambda x: x.split())

C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\828393114.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [29]:
movies['overview']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [30]:

# Function to remove spaces between values to treat as a single chunk to avoid the redundancy and making easy to analysis
def removeSpace(dataList):
    list = []
    for i in dataList:
        list.append(i.replace(" ", ""))
    return list

In [31]:
movies['cast'] = movies['cast'].apply(removeSpace)
movies['keywords'] = movies['keywords'].apply(removeSpace)
movies['crew'] = movies['crew'].apply(removeSpace)
movies['genres'] = movies['genres'].apply(removeSpace)

C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\3525679710.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(removeSpace)
C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\3525679710.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(removeSpace)
C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\3525679710.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(removeSpace)
C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\3525679710.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(removeSpace)

In [32]:
movies['cast']

0       [SamWorthington, ZoeSaldana, SigourneyWeaver, ...
1       [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...
2       [DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...
3       [ChristianBale, MichaelCaine, GaryOldman, Anne...
4       [TaylorKitsch, LynnCollins, SamanthaMorton, Wi...
                              ...
4804    [CarlosGallardo, JaimedeHoyos, PeterMarquardt,...
4805    [EdwardBurns, KerryBishÃ©, MarshaDietlein, Cait...
4806    [EricMabius, KristinBooth, CrystalLowe, GeoffG...
4807    [DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...
4808    [DrewBarrymore, BrianHerzlinger, CoreyFeldman,...
Name: cast, Length: 4806, dtype: object

In [33]:
movies['keywords']

0       [cultureclash, future, spacewar, spacecolony, ...
1       [ocean, drugabuse, exoticisland, eastindiatrad...
2       [spy, basedonnovel, secretagent, sequel, mi6, ...
3       [dccomics, crimefighter, terrorist, secretiden...
4       [basedonnovel, mars, medallion, spacetravel, p...
                              ...
4804    [unitedstatesâ€“mexicobarrier, legs, arms, paper...
4805                                                   []
4806    [date, loveatfirstsight, narration, investigat...
4807                                                   []
4808             [obsession, camcorder, crush, dreamgirl]
Name: keywords, Length: 4806, dtype: object

In [34]:
movies['crew']

0                              [JamesCameron]
1                             [GoreVerbinski]
2                                 [SamMendes]
3                          [ChristopherNolan]
4                             [AndrewStanton]
                        ...
4804                        [RobertRodriguez]
4805                            [EdwardBurns]
4806                             [ScottSmith]
4807                             [DanielHsia]
4808    [BrianHerzlinger, JonGunn, BrettWinn]
Name: crew, Length: 4806, dtype: object

In [35]:
movies['genres']

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [36]:
# Adding all other salient fields to get a composite list called "tags"
movies['tags'] = movies['overview'].astype(str) + ' ' + movies['genres'].astype(str) + ' ' + movies['keywords'].astype(str) + ' ' + movies['cast'].astype(str) + ' ' + movies['crew'].astype(str)

C:\Users\Arjyel\AppData\Local\Temp\ipykernel_3120\4159865421.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'].astype(str) + ' ' + movies['genres'].astype(str) + ' ' + movies['keywords'].astype(str) + ' ' + movies['cast'].astype(str) + ' ' + movies['crew'].astype(str)

In [37]:
movies['tags']

0       ['In', 'the', '22nd', 'century,', 'a', 'parapl...
1       ['Captain', 'Barbossa,', 'long', 'believed', '...
2       ['A', 'cryptic', 'message', 'from', 'Bondâ€™s', ...
3       ['Following', 'the', 'death', 'of', 'District'...
4       ['John', 'Carter', 'is', 'a', 'war-weary,', 'f...
                              ...
4804    ['El', 'Mariachi', 'just', 'wants', 'to', 'pla...
4805    ['A', 'newlywed', "couple's", 'honeymoon', 'is...
4806    ['"Signed,', 'Sealed,', 'Delivered"', 'introdu...
4807    ['When', 'ambitious', 'New', 'York', 'attorney...
4808    ['Ever', 'since', 'the', 'second', 'grade', 'w...
Name: tags, Length: 4806, dtype: object

In [38]:
new_movies = movies.drop(columns=['overview', 'genres', 'keywords', 'cast', 'crew'])

In [39]:
new_movies

,movie_id,title,tags
0,19995,Avatar,"['In', 'the', '22nd', 'century,', 'a', 'parapl..."
1,285,Pirates of the Caribbean: At World's End,"['Captain', 'Barbossa,', 'long', 'believed', '..."
2,206647,Spectre,"['A', 'cryptic', 'message', 'from', 'Bondâ€™s', ..."
3,49026,The Dark Knight Rises,"['Following', 'the', 'death', 'of', 'District'..."
4,49529,John Carter,"['John', 'Carter', 'is', 'a', 'war-weary,', 'f..."
...,...,...,...
4804,9367,El Mariachi,"['El', 'Mariachi', 'just', 'wants', 'to', 'pla..."
4805,72766,Newlyweds,"['A', 'newlywed', ""couple's"", 'honeymoon', 'is..."
4806,231617,"Signed, Sealed, Delivered","['""Signed,', 'Sealed,', 'Delivered""', 'introdu..."
4807,126186,Shanghai Calling,"['When', 'ambitious', 'New', 'York', 'attorney..."
4808,25975,My Date with Drew,"['Ever', 'since', 'the', 'second', 'grade', 'w..."

In [40]:
new_movies['tags'] = new_movies['tags'].apply(lambda x: "".join(x))

In [41]:
new_movies['tags']

0       ['In', 'the', '22nd', 'century,', 'a', 'parapl...
1       ['Captain', 'Barbossa,', 'long', 'believed', '...
2       ['A', 'cryptic', 'message', 'from', 'Bondâ€™s', ...
3       ['Following', 'the', 'death', 'of', 'District'...
4       ['John', 'Carter', 'is', 'a', 'war-weary,', 'f...
                              ...
4804    ['El', 'Mariachi', 'just', 'wants', 'to', 'pla...
4805    ['A', 'newlywed', "couple's", 'honeymoon', 'is...
4806    ['"Signed,', 'Sealed,', 'Delivered"', 'introdu...
4807    ['When', 'ambitious', 'New', 'York', 'attorney...
4808    ['Ever', 'since', 'the', 'second', 'grade', 'w...
Name: tags, Length: 4806, dtype: object

In [42]:
new_movies['tags'][0]

"['In', 'the', '22nd', 'century,', 'a', 'paraplegic', 'Marine', 'is', 'dispatched', 'to', 'the', 'moon', 'Pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.'] ['Action', 'Adventure', 'Fantasy', 'ScienceFiction'] ['cultureclash', 'future', 'spacewar', 'spacecolony', 'society', 'spacetravel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alienplanet', 'cgi', 'marine', 'soldier', 'battle', 'loveaffair', 'antiwar', 'powerrelations', 'mindandsoul', '3d'] ['SamWorthington', 'ZoeSaldana', 'SigourneyWeaver', 'StephenLang', 'MichelleRodriguez', 'GiovanniRibisi', 'JoelDavidMoore', 'CCHPounder', 'WesStudi', 'LazAlonso', 'DileepRao', 'MattGerald', 'SeanAnthonyMoran', 'JasonWhyte', 'ScottLawrence', 'KellyKilgour', 'JamesPatrickPitt', 'SeanPatrickMurphy', 'PeterDillon', 'KevinDorman', 'KelsonHenderson', 'DavidVanHorn', 'JacobTomuri', 'MichaelBlain-Rozgay', 'JonCurry', 'LukeHawker', 'WoodySchultz', 'PeterMensah', 'SoniaYee', 'JahnelCurfman', 'IlramChoi', 'KylaWarren', 'LisaRoumain', 'DebraWilson', 'ChrisMala', 'TaylorKibby', 'JodieLandau', 'JulieLamm', 'CullenB.Madden', 'JosephBradyMadden', 'FrankieTorres', 'AustinWilson', 'SaraWilson', 'TamicaWashington-Miller', 'LucyBriant', 'NathanMeister', 'GerryBlair', 'MatthewChamberlain', 'PaulYates', 'WrayWilson', 'JamesGaylyn', 'MelvinLenoClarkIII', 'CarvonFutrell', 'BrandonJelkes', 'MicahMoch', 'HanniyahMuhammad', 'ChristopherNolen', 'ChristaOliver', 'AprilMarieThomas', 'BravitaA.Threatt', 'ColinBleasdale', 'MikeBodnar', 'MattClayton', 'NicoleDionne', 'JamieHarrison', 'AllanHenry', 'AnthonyIngruber', 'AshleyJeffery', 'DeanKnowsley', 'JosephMika-Hunt', 'TerryNotary', 'KaiPantano', 'LoganPithyou', 'StuartPollock', 'Raja', 'GarethRuck', 'RhianSheehan', 'T.J.Storm', 'JodieTaylor', 'AliciaVela-Bailey', 'RichardWhiteside', 'NikieZambo', 'JuleneRenee'] ['JamesCameron']"

In [43]:
new_movies['tags'] = new_movies['tags'].apply(lambda x: x.lower())

In [44]:
new_movies['tags'][0]

"['in', 'the', '22nd', 'century,', 'a', 'paraplegic', 'marine', 'is', 'dispatched', 'to', 'the', 'moon', 'pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.'] ['action', 'adventure', 'fantasy', 'sciencefiction'] ['cultureclash', 'future', 'spacewar', 'spacecolony', 'society', 'spacetravel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alienplanet', 'cgi', 'marine', 'soldier', 'battle', 'loveaffair', 'antiwar', 'powerrelations', 'mindandsoul', '3d'] ['samworthington', 'zoesaldana', 'sigourneyweaver', 'stephenlang', 'michellerodriguez', 'giovanniribisi', 'joeldavidmoore', 'cchpounder', 'wesstudi', 'lazalonso', 'dileeprao', 'mattgerald', 'seananthonymoran', 'jasonwhyte', 'scottlawrence', 'kellykilgour', 'jamespatrickpitt', 'seanpatrickmurphy', 'peterdillon', 'kevindorman', 'kelsonhenderson', 'davidvanhorn', 'jacobtomuri', 'michaelblain-rozgay', 'joncurry', 'lukehawker', 'woodyschultz', 'petermensah', 'soniayee', 'jahnelcurfman', 'ilramchoi', 'kylawarren', 'lisaroumain', 'debrawilson', 'chrismala', 'taylorkibby', 'jodielandau', 'julielamm', 'cullenb.madden', 'josephbradymadden', 'frankietorres', 'austinwilson', 'sarawilson', 'tamicawashington-miller', 'lucybriant', 'nathanmeister', 'gerryblair', 'matthewchamberlain', 'paulyates', 'wraywilson', 'jamesgaylyn', 'melvinlenoclarkiii', 'carvonfutrell', 'brandonjelkes', 'micahmoch', 'hanniyahmuhammad', 'christophernolen', 'christaoliver', 'aprilmariethomas', 'bravitaa.threatt', 'colinbleasdale', 'mikebodnar', 'mattclayton', 'nicoledionne', 'jamieharrison', 'allanhenry', 'anthonyingruber', 'ashleyjeffery', 'deanknowsley', 'josephmika-hunt', 'terrynotary', 'kaipantano', 'loganpithyou', 'stuartpollock', 'raja', 'garethruck', 'rhiansheehan', 't.j.storm', 'jodietaylor', 'aliciavela-bailey', 'richardwhiteside', 'nikiezambo', 'julenerenee'] ['jamescameron']"

In [45]:
# handeling stem things in data
# for eg: "walk walking walked walks" are converted to "walk walk walk walk"

def stemFunc(tagValues):
    list = []
    for i in tagValues.split():
        list.append(ps.stem(i))
    return " ".join(list)

In [46]:
new_movies['tags'] = new_movies['tags'].apply(stemFunc)

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

# Convert a collection of text documents to a matrix of token counts
# Removing the stop words
cv = CountVectorizer(max_features=6000, stop_words='english')

# Making arrays of vector of all the tags data i.e. converting text to a vector in 6000 Dimension
vector = cv.fit_transform(new_movies['tags']).toarray()
# Thus vector is of (4806, 6000) dimension

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

# Calculation of cosine similarities amongst vectors to calculate their distances to find the similarities among the movies
# It will calculate cosine distance (not Euclidean distance) of each movie to every other movies
similarVect = cosine_similarity(vector)

In [49]:
def recommendMovies(search_movie):
    index_movie = new_movies[new_movies['title'] == search_movie].index[0]  # Fetching index of searched movie
    optimumDist = similarVect[index_movie]  # getting cosine value of that movie
    list_movies = sorted(list(enumerate(optimumDist)), reverse=True, key=lambda x: x[1])[1:6]
    # sorting the cosine values in descending order because highest value are most matched
    # enumerate function retain the index of the movies  even after sorting by creating tuple of (<index>,<cosine distance>)
    # lamda function used to sort on the basis of <cosine distance> rather than <index>

    for i in list_movies:
        print(new_movies.iloc[i[0]].title)

In [50]:
# This function takes an input from user filters out the special characters
# calls the function recommendMovies() to provide suitable recommendations
def searchFunc():
    count = 0
    search = input('Enter a Movie Name: ')
    # search="Amazing-SpidermA"
    wordsList = search.split()
    searchOptimize = ""
    for j in wordsList:
        searchOptimize = ".*".join([searchOptimize, j])
    for i in new_movies['title']:
        x = re.search(re.sub("[$@&-:' ?,#_.!+(){}]", "", searchOptimize.upper()),
                      re.sub("[$@&-:' ?,#_.!+(){}]", "", i.upper()))  # Filters out the special characters
        if x:
            print('You Searched:', search)
            print('Search [', count + 1, ']=> Did You Mean?:', i)
            print('Recommended Movies are:')
            while (recommendMovies(i) != None): print(recommendMovies(i))
            print("***************************************************")
            count += 1
    if count == 0:
        print('The Movie ', search, ' is Not Available!!')

In [51]:
searchFunc()

Enter a Movie Name: ama
You Searched: ama
Search [ 1 ]=> Did You Mean?: The Amazing Spider-Man
Recommended Movies are:
The Amazing Spider-Man 2
Spider-Man 3
Spider-Man
Hook
Pan
***************************************************
You Searched: ama
Search [ 2 ]=> Did You Mean?: The Amazing Spider-Man 2
Recommended Movies are:
The Amazing Spider-Man
Spider-Man 3
Pan
Spider-Man
Forgetting Sarah Marshall
***************************************************
You Searched: ama
Search [ 3 ]=> Did You Mean?: Cinderella Man
Recommended Movies are:
Ali
Rocky Balboa
The Longshots
Raging Bull
The Perfect Game
***************************************************
You Searched: ama
Search [ 4 ]=> Did You Mean?: Collateral Damage
Recommended Movies are:
3 Days to Kill
Nighthawks
The Kingdom
I Am Wrath
The Algerian
***************************************************
You Searched: ama
Search [ 5 ]=> Did You Mean?: Sweet Home Alabama
Recommended Movies are:
There's Always Woodstock
It's Complicated
Snow Day
And Then Came Love
Supporting Characters
***************************************************
You Searched: ama
Search [ 6 ]=> Did You Mean?: A Man Apart
Recommended Movies are:
Oldboy
Furious 7
Stranded
I Am Wrath
Perrierâ€™s Bounty
***************************************************
You Searched: ama
Search [ 7 ]=> Did You Mean?: Baby Mama
Recommended Movies are:
L!fe Happens
Living Out Loud
Next Stop Wonderland
Three Men and a Baby
I Love You, Man
***************************************************
You Searched: ama
Search [ 8 ]=> Did You Mean?: A Madea Christmas
Recommended Movies are:
A Charlie Brown Christmas
Christmas with the Kranks
Madea Goes to Jail
Madea's Witness Protection
Arthur Christmas
***************************************************
You Searched: ama
Search [ 9 ]=> Did You Mean?: Think Like a Man Too
Recommended Movies are:
Think Like a Man
About Last Night
My Big Fat Greek Wedding 2
Not Easily Broken
Top Five
***************************************************
You Searched: ama
Search [ 10 ]=> Did You Mean?: Team America: World Police
Recommended Movies are:
G-Force
The Game of Their Lives
The Triplets of Belleville
Miracle
Signed, Sealed, Delivered
***************************************************
You Searched: ama
Search [ 11 ]=> Did You Mean?: Ramanujan
Recommended Movies are:
Ip Man 3
Coal Miner's Daughter
A Passage to India
The Young Victoria
Airlift
***************************************************
You Searched: ama
Search [ 12 ]=> Did You Mean?: Amadeus
Recommended Movies are:
Nowhere Boy
Scott Walker: 30 Century Man
Song One
Once
Mr. Holland's Opus
***************************************************
You Searched: ama
Search [ 13 ]=> Did You Mean?: The Tailor of Panama
Recommended Movies are:
The Contender
Absolute Power
Gabriela
Selma
Dutch Kills
***************************************************
You Searched: ama
Search [ 14 ]=> Did You Mean?: Juwanna Mann
Recommended Movies are:
Space Jam
Love & Basketball
The Other Dream Team
Coach Carter
Brotherly Love
***************************************************
You Searched: ama
Search [ 15 ]=> Did You Mean?: Mama
Recommended Movies are:
Train
The Haunting in Connecticut 2: Ghosts of Georgia
The Last Exorcism Part II
The Purge: Election Year
Little Nicholas
***************************************************
You Searched: ama
Search [ 16 ]=> Did You Mean?: Confessions of a Teenage Drama Queen
Recommended Movies are:
LOL
Snow Day
Sugar Town
Mutual Appreciation
Four Single Fathers
***************************************************
You Searched: ama
Search [ 17 ]=> Did You Mean?: Crazy in Alabama
Recommended Movies are:
Evita
I Am Wrath
Get Low
Drowning Mona
Should've Been Romeo
***************************************************
You Searched: ama
Search [ 18 ]=> Did You Mean?: The Boy in the Striped Pyjamas
Recommended Movies are:
The Hunt
City By The Sea
Mi America
Amidst the Devil's Wings
The Immigrant
***************************************************
You Searched: ama
Search [ 19 ]=> Did You Mean?: Think Like a Man
Recommended Movies are:
Barbershop 2:  Back in Business
The Salon
The Crime of Padre Amaro
My Girl
Wish I Was Here
***************************************************
You Searched: ama
Search [ 20 ]=> Did You Mean?: Aquamarine
Recommended Movies are:
The Spectacular Now
I Love You, Beth Cooper
Beastly
The DUFF
Now Is Good
***************************************************
You Searched: ama
Search [ 21 ]=> Did You Mean?: Space Battleship Yamato
Recommended Movies are:
The Quiet American
Nicholas Nickleby
No Escape
This Christmas
Journey from the Fall
***************************************************
You Searched: ama
Search [ 22 ]=> Did You Mean?: 10 Days in a Madhouse
Recommended Movies are:
Room
Partition
The Tree of Life
Forrest Gump
Little Boy
***************************************************
You Searched: ama
Search [ 23 ]=> Did You Mean?: It's a Mad, Mad, Mad, Mad World
Recommended Movies are:
It's a Wonderful Afterlife
Straight A's
Running Forever
Lovely & Amazing
Lady in White
***************************************************
You Searched: ama
Search [ 24 ]=> Did You Mean?: Ultramarines: A Warhammer 40,000 Movie
Recommended Movies are:
Spellbound
Before I Go to Sleep
Extreme Measures
The Dead Zone
Godsend
***************************************************
You Searched: ama
Search [ 25 ]=> Did You Mean?: Namastey London
Recommended Movies are:
Miss Julie
Gandhi
Michael Collins
Bloody Sunday
Angela's Ashes
***************************************************
You Searched: ama
Search [ 26 ]=> Did You Mean?: The Extra Man
Recommended Movies are:
Tango
Stories of Our Lives
20 Dates
Incident at Loch Ness
Juliet and Alfa Romeo
***************************************************
You Searched: ama
Search [ 27 ]=> Did You Mean?: Diary of a Mad Black Woman
Recommended Movies are:
The Pianist
The Man from Snowy River
Elmer Gantry
Elza
The Crime of Padre Amaro
***************************************************
You Searched: ama
Search [ 28 ]=> Did You Mean?: A Man for All Seasons
Recommended Movies are:
Bamboozled
Death to Smoochy
10 Days in a Madhouse
Top Five
The Postman Always Rings Twice
***************************************************
You Searched: ama
Search [ 29 ]=> Did You Mean?: Kama Sutra - A Tale of Love
Recommended Movies are:
Pieces of April
The Out-of-Towners
Four Single Fathers
Boynton Beach Club
Everything Must Go
***************************************************
You Searched: ama
Search [ 30 ]=> Did You Mean?: 2016: Obama's America
Recommended Movies are:
Larry Crowne
Fame
Begin Again
Bandslam
ABCD (Any Body Can Dance)
***************************************************
You Searched: ama
Search [ 31 ]=> Did You Mean?: Chicken Tikka Masala
Recommended Movies are:
Raising Helen
The Last Five Years
Sweet Home Alabama
Real Women Have Curves
My Last Day Without You
***************************************************
You Searched: ama
Search [ 32 ]=> Did You Mean?: The Crime of Padre Amaro
Recommended Movies are:
Dawn of the Planet of the Apes
Conquest of the Planet of the Apes
Beneath the Planet of the Apes
Planet of the Apes
9
***************************************************
You Searched: ama
Search [ 33 ]=> Did You Mean?: The Amazing Catfish
Recommended Movies are:
What's Eating Gilbert Grape
Partition
Under the Same Moon
Radio Flyer
Two Lovers and a Bear
***************************************************
You Searched: ama
Search [ 34 ]=> Did You Mean?: Martha Marcy May Marlene
Recommended Movies are:
Among Giants
Shinjuku Incident
Four Single Fathers
Autumn in New York
Shopgirl
***************************************************
You Searched: ama
Search [ 35 ]=> Did You Mean?: Osama
Recommended Movies are:
Harsh Times
Trees Lounge
Stripes
Funny Ha Ha
The Jerky Boys
***************************************************
You Searched: ama
Search [ 36 ]=> Did You Mean?: Nothing But a Man
Recommended Movies are:
Shanghai Noon
The Possession
Baahubali: The Beginning
Brave
2016: Obama's America
***************************************************
You Searched: ama
Search [ 37 ]=> Did You Mean?: Lovely & Amazing
Recommended Movies are:
Boynton Beach Club
The Land Girls
Love Letters
Code 46
Vamps
***************************************************
You Searched: ama
Search [ 38 ]=> Did You Mean?: Samantha: An American Girl Holiday
Recommended Movies are:
Diary of a Mad Black Woman
This Is Martin Bonner
Hell's Angels
Brigham City
Limbo
***************************************************